version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:89562310@db:5432/coursesDB  # Use 'db' as the hostname
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 89562310
      POSTGRES_DB: coursesDB
    ports:
      - "5433:5432"  # Map the internal 5432 to 5433 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
