"""Add courseID to Course model

Revision ID: 110f601a228f
Revises: 
Create Date: 2024-08-20 22:15:23.569599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110f601a228f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courseID', sa.String(length=50), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('courseID')

    # ### end Alembic commands ###
