"""Initial migration

Revision ID: 21c9b23df5bc
Revises: 
Create Date: 2024-09-06 12:42:33.081765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c9b23df5bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture_time', schema=None) as batch_op:
        batch_op.drop_constraint('lecture_time_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    with op.batch_alter_table('practice_time', schema=None) as batch_op:
        batch_op.drop_constraint('practice_time_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_time', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('practice_time_course_id_fkey', 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lecture_time', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lecture_time_course_id_fkey', 'course', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
