"""Add LectureTime model and update Course model

Revision ID: 517144da1a88
Revises: 110f601a228f
Create Date: 2024-08-20 22:27:34.009975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517144da1a88'
down_revision = '110f601a228f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_day', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('practice_time', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('practice_time')
        batch_op.drop_column('practice_day')

    op.drop_table('lecture_time')
    # ### end Alembic commands ###
