"""Recreate all tables

Revision ID: eb21fb0eec99
Revises: e480c268362f
Create Date: 2024-08-31 21:57:16.038133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb21fb0eec99'
down_revision = 'e480c268362f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_time')
    op.drop_table('course')
    op.drop_table('practice_time')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_pref', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority_course_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority_course_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_course_day', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('no_course_time_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('no_course_time_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['priority_course_1'], ['course.id'], name='user_preferences_priority_course_1_fkey'),
    sa.ForeignKeyConstraint(['priority_course_2'], ['course.id'], name='user_preferences_priority_course_2_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_preferences_pkey')
    )
    op.create_table('practice_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('building', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('classroom', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='practice_time_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='practice_time_pkey')
    )
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('course_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='course_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('lecture_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('building', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('classroom', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='lecture_time_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lecture_time_pkey')
    )
    # ### end Alembic commands ###
