"""Fix app_user table migration

Revision ID: fe69b9ae3bcc
Revises: d834f1922dcf
Create Date: 2024-09-21 18:04:03.605731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe69b9ae3bcc'
down_revision = 'd834f1922dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_user_pkey'),
    sa.UniqueConstraint('email', name='app_user_email_key'),
    sa.UniqueConstraint('username', name='app_user_username_key')
    )
    # ### end Alembic commands ###
